dist: noble
script: uname -r 
install: skip
services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - psql -c "SELECT version();" -U postgres

addons:
  postgresql: "16"
